services:
  postgres:
    ports:
      - "5432:5432"

  api:
    environment:
      WEB_BASE_URL: http://127.0.0.1:5173
    ports:
      - "4000:4000"

  web:
    environment:
      VITE_API_URL: http://127.0.0.1:4000/graphql
      WEB_BASE_URL: http://127.0.0.1:5173
    ports:
      - "5173:5173"
